---

version: 2

build:
  image: latest

python:
  version: 3.6
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
